### ISSUE TITLE
swap failed CORS errror

### ISSUE THREAD

**Issue by sahiruha** [raydium-io/raydium-api#2]
mathwallet & Ray is CORS error .
please check this issue.

![IMG_3036](https://user-images.githubusercontent.com/7632949/116641150-1a408280-a9a7-11eb-8615-19b2fb379ef9.PNG)

![IMG_3037](https://user-images.githubusercontent.com/7632949/116641161-1e6ca000-a9a7-11eb-8c73-6bc5becdd7ac.PNG)

**Comment by sahiruha** [comment]
If the content is not appropriate, please reject it.

**Comment by TimonPeng** [comment]
Not this repo.
